{\rtf1\ansi\ansicpg1251\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red15\green112\blue1;\red255\green255\blue255;\red37\green37\blue37;
\red0\green0\blue255;\red144\green1\blue18;\red60\green60\blue59;\red250\green252\blue255;}
{\*\expandedcolortbl;;\cssrgb\c0\c50196\c0;\cssrgb\c100000\c100000\c100000;\cssrgb\c19216\c19216\c19216;
\cssrgb\c0\c0\c100000;\cssrgb\c63922\c8235\c8235;\cssrgb\c30196\c30196\c29804;\cssrgb\c98431\c99216\c100000;}
\paperw11900\paperh16840\margl1440\margr1440\vieww28600\viewh15020\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf2 \cb3 \expnd0\expndtw0\kerning0
# my global config
\f1 \cf4 \
\pard\pardeftab720\partightenfactor0

\f0 \cf5 global
\f1 \cf4 :\
  scrape_interval: 15s 
\f0 \cf2 # Set the scrape interval to every 15 seconds. Default is every 1 minute.
\f1 \cf4 \
  evaluation_interval: 15s 
\f0 \cf2 # Evaluate rules every 15 seconds. The default is every 1 minute.
\f1 \cf4 \
  
\f0 \cf2 # scrape_timeout is set to the global default (10s).
\f1 \cf4 \
\
\pard\pardeftab720\partightenfactor0

\f0 \cf2 # Alertmanager configuration
\f1 \cf4 \
alerting:\
  alertmanagers:\
    - static_configs:\
        - targets:\
          
\f0 \cf2 # - alertmanager:9093
\f1 \cf4 \
\

\f0 \cf2 # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
\f1 \cf4 \
rule_files:\
  
\f0 \cf2 # - "first_rules.yml"
\f1 \cf4 \
  
\f0 \cf2 # - "second_rules.yml"
\f1 \cf4 \
\

\f0 \cf2 # A scrape configuration containing exactly one endpoint to scrape:
\f1 \cf4 \

\f0 \cf2 # Here it's Prometheus itself.
\f1 \cf4 \
scrape_configs:\
  
\f0 \cf2 # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
\f1 \cf4 \
  - job_name: 
\f0 \cf6 "prometheus"
\f1 \cf4 \
\
    
\f0 \cf2 # metrics_path defaults to '/metrics'
\f1 \cf4 \
    
\f0 \cf2 # scheme defaults to 'http'.
\f1 \cf4 \
\
    static_configs:\
      - targets: [
\f0 \cf6 "localhost:9090"
\f1 \cf4 ]\
\pard\pardeftab720\partightenfactor0

\fs28 \cf7 \cb8   
\fs26 \cf4 \cb3 \
  - job_name: 
\f0 \cf6 "
\f1 \cf4 pushgateway
\f0 \cf6 "
\f1 \cf4 \
    honor_labels: false\
    static_configs:\
      - targets: [
\f0 \cf6 "
\f1 \cf4 localhost:9091
\f0 \cf6 "
\f1 \cf4 ]\
        labels:\
        pushgateway_instance: metricfire}